package hibernate;
// Generated 23-ene-2018 8:49:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AsAeropuertos generated by hbm2java
 */
public class ASAeropuertos  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String ciudad;
     private String pais;
     private Set asVuelosesForAeropuertoSalida = new HashSet(0);
     private Set asVuelosesForAeropuertoLlegada = new HashSet(0);

    public ASAeropuertos() {
    }

	
    public ASAeropuertos(String codigo, String nombre, String ciudad, String pais) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.ciudad = ciudad;
        this.pais = pais;
    }
    public ASAeropuertos(String codigo, String nombre, String ciudad, String pais, Set asVuelosesForAeropuertoSalida, Set asVuelosesForAeropuertoLlegada) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.ciudad = ciudad;
       this.pais = pais;
       this.asVuelosesForAeropuertoSalida = asVuelosesForAeropuertoSalida;
       this.asVuelosesForAeropuertoLlegada = asVuelosesForAeropuertoLlegada;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getAsVuelosesForAeropuertoSalida() {
        return this.asVuelosesForAeropuertoSalida;
    }
    
    public void setAsVuelosesForAeropuertoSalida(Set asVuelosesForAeropuertoSalida) {
        this.asVuelosesForAeropuertoSalida = asVuelosesForAeropuertoSalida;
    }
    public Set getAsVuelosesForAeropuertoLlegada() {
        return this.asVuelosesForAeropuertoLlegada;
    }
    
    public void setAsVuelosesForAeropuertoLlegada(Set asVuelosesForAeropuertoLlegada) {
        this.asVuelosesForAeropuertoLlegada = asVuelosesForAeropuertoLlegada;
    }




}


