package hibernate;
// Generated 23-ene-2018 8:49:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AsFabricantes generated by hbm2java
 */
public class AsFabricantes  implements java.io.Serializable {


     private byte idFabricante;
     private String nombre;
     private Set asAvioneses = new HashSet(0);

    public AsFabricantes() {
    }

	
    public AsFabricantes(byte idFabricante, String nombre) {
        this.idFabricante = idFabricante;
        this.nombre = nombre;
    }
    public AsFabricantes(byte idFabricante, String nombre, Set asAvioneses) {
       this.idFabricante = idFabricante;
       this.nombre = nombre;
       this.asAvioneses = asAvioneses;
    }
   
    public byte getIdFabricante() {
        return this.idFabricante;
    }
    
    public void setIdFabricante(byte idFabricante) {
        this.idFabricante = idFabricante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAsAvioneses() {
        return this.asAvioneses;
    }
    
    public void setAsAvioneses(Set asAvioneses) {
        this.asAvioneses = asAvioneses;
    }




}


