package hibernate;
// Generated 23-ene-2018 8:49:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * AsIncidencias generated by hbm2java
 */
public class AsIncidencias  implements java.io.Serializable {


     private int id;
     private AsAviones asAviones;
     private Date momento;
     private BigDecimal latitud;
     private BigDecimal longitud;
     private Serializable descripcion;
     private char tipo;

    public AsIncidencias() {
    }

	
    public AsIncidencias(int id, AsAviones asAviones, Date momento, Serializable descripcion, char tipo) {
        this.id = id;
        this.asAviones = asAviones;
        this.momento = momento;
        this.descripcion = descripcion;
        this.tipo = tipo;
    }
    public AsIncidencias(int id, AsAviones asAviones, Date momento, BigDecimal latitud, BigDecimal longitud, Serializable descripcion, char tipo) {
       this.id = id;
       this.asAviones = asAviones;
       this.momento = momento;
       this.latitud = latitud;
       this.longitud = longitud;
       this.descripcion = descripcion;
       this.tipo = tipo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public AsAviones getAsAviones() {
        return this.asAviones;
    }
    
    public void setAsAviones(AsAviones asAviones) {
        this.asAviones = asAviones;
    }
    public Date getMomento() {
        return this.momento;
    }
    
    public void setMomento(Date momento) {
        this.momento = momento;
    }
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }
    public Serializable getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Serializable descripcion) {
        this.descripcion = descripcion;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }




}


